### ISSUE TITLE
Tools Page

### ISSUE THREAD

**Issue by Jbcampbe** [Renascentinc/retina#185]
# To-Do's

### Components
- [x] build tool search component
- [x] build tool search result component

# Verification
### Browsers
- [ ] IE 11
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Safari IOS
- [ ] Chrome IOS
- [ ] Chrome Android

### Correct Behavior For Different Permissions
- [ ] Admin
- [ ] Standard

**Comment by Jbcampbe** [comment]
# Verification

## Browsers
- [ ] IE 11
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Safari IOS
- [ ] Chrome IOS
- [ ] Chrome Android

## Permissions
- [ ] Admin
- [ ] Standard

## Tests
- [ ] Unit/Integration tests
